apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: backend
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pearlicia/backend:v2.0.0
        imagePullPolicy: Always
        ports:
        - name: backendport
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: backendport
      nodePort: 30030
  type: NodePort