apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
  labels:
    name: frontend
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: pearlicia/frontend:v2.0.0
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: frontendport
      nodePort: 30031
  type: NodePort