apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: pearlicia/trial:v2.0.0
        imagePullPolicy: Always
        ports:
        - name: trialport
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: trial
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      protocol: TCP
      port: 80
      targetPort: trialport
      nodePort: 30032
  type: NodePort
